const HTTP_CODES = {
  HTTP_SUCCESS: 200,
  HTTP_CLIENT_ERROR: 400,
  HTTP_INVALID_TOKEN: 401,
  HTTP_NOT_AUTHORIZED: 403,
  HTTP_NOT_FOUND: 404,
  HTTP_SERVER_ERROR: 500,
};

module.exports = { HTTP_CODES };
